name: react-component-library
files:
  - 'packages/**/*.*'
  - 'scripts/*'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /react-component-library-description/g
    to: A compact React component designed to handle dynamic content, while securing a scroll position at the bottom.
  - from: /react-component-library/g
    to: ${PROJECT_NAME}
  - from: /Anonymous/g
    to: ReactScrollPin
